services:
  app:
    build:
      context: .
      target: production
    container_name: vue-app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development environment with hot-reload
  dev:
    build:
      context: .
      target: build
    container_name: vue-app-dev
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: bun run dev --host
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  # Uncomment and configure if you have a backend API
  # api:
  #   build:
  #     context: ./api
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
